version: '3'

services:

  reviewapp:
    image: reviewapp:latest
    container_name: reviewapp
    restart: always

    ports:
      - 127.0.0.1:5191:80

    volumes:
      - reviewapp_database:/app/DatabaseRelease

    networks:
      - reviewapp_reviewapp-net

volumes:
  # Database reside here
  reviewapp_database:

networks:
  reviewapp_reviewapp-net:
    driver: bridge
    external: true